import { Router } from 'express';
import products from './products.js';
import branches from './branches.js';
import sales from './sales.js';
import refunds from './refunds.js';
import stock from './stock.js';
import suppliers from './suppliers.js';
import customers from './customers.js';
import auth from './auth.js';
import settings from './settings.js';
import users from './users.js';
import serverLogs from './serverLogs.js';
import audits from './audits.js';
import cashsessions from './cashsessions.js';
import expenses from './expenses.js';
import invoices from './invoices.js';
import purchases from './purchases.js';
import transfers from './transfers.js';
import adjustments from './adjustments.js';
import approvals from './approvals.js';
import wholesale from './wholesale.js';
import credits from './credits.js';
import productUnits from './productUnits.js';
import reconciliationAccounts from './reconciliationAccounts.js';
import cashReconciliations from './cashReconciliations.js';
import tenants from './tenants.js';

const router = Router();
router.use('/products', products);
router.use('/branches', branches);
router.use('/sales', sales);
router.use('/refunds', refunds);
router.use('/stock', stock);
router.use('/suppliers', suppliers);
router.use('/customers', customers);
router.use('/auth', auth);
router.use('/settings', settings);
router.use('/users', users);
router.use('/server-logs', serverLogs);
router.use('/audits', audits);
router.use('/cashsessions', cashsessions);
router.use('/expenses', expenses);
router.use('/invoices', invoices);
router.use('/purchases', purchases);
router.use('/transfers', transfers);
router.use('/adjustments', adjustments);
router.use('/approvals', approvals);
router.use('/wholesale', wholesale);
router.use('/credits', credits);
router.use('/product-units', productUnits);
router.use('/reconciliation-accounts', reconciliationAccounts);
router.use('/cash-reconciliations', cashReconciliations);
router.use('/tenants', tenants);

export default router;
