export const TENANT_GRANT_CATALOG = [
  { key: 'view_dashboard', label: 'Dashboard' },
  { key: 'view_pos', label: 'POS' },
  { key: 'view_wholesale_pos', label: 'Wholesale POS' },
  { key: 'view_retail_price', label: 'Retail Price Visibility' },
  { key: 'view_wholesale_price', label: 'Wholesale Price Visibility' },
  { key: 'view_agent_price', label: 'Agent Price Visibility' },
  { key: 'view_sales', label: 'Sales' },
  { key: 'add_sales', label: 'Sales: Add' },
  { key: 'view_products', label: 'Products' },
  { key: 'add_products', label: 'Products: Add' },
  { key: 'edit_products', label: 'Products: Edit' },
  { key: 'view_inventory', label: 'Inventory' },
  { key: 'edit_inventory', label: 'Inventory: Edit' },
  { key: 'view_serialized_inventory', label: 'Serialized Inventory' },
  { key: 'view_labels', label: 'Labels' },
  { key: 'view_purchases', label: 'Purchases' },
  { key: 'add_purchases', label: 'Purchases: Add' },
  { key: 'edit_purchases', label: 'Purchases: Edit' },
  { key: 'approve_purchases', label: 'Purchases: Approve' },
  { key: 'view_transfers', label: 'Transfers' },
  { key: 'add_transfers', label: 'Transfers: Add' },
  { key: 'edit_transfers', label: 'Transfers: Edit' },
  { key: 'approve_transfers', label: 'Transfers: Approve' },
  { key: 'view_adjustments', label: 'Adjustments' },
  { key: 'add_adjustments', label: 'Adjustments: Add' },
  { key: 'edit_adjustments', label: 'Adjustments: Edit' },
  { key: 'approve_adjustments', label: 'Adjustments: Approve' },
  { key: 'view_suppliers', label: 'Suppliers' },
  { key: 'add_suppliers', label: 'Suppliers: Add' },
  { key: 'edit_suppliers', label: 'Suppliers: Edit' },
  { key: 'view_customers', label: 'Customers' },
  { key: 'add_customers', label: 'Customers: Add' },
  { key: 'edit_customers', label: 'Customers: Edit' },
  { key: 'view_credit_control', label: 'Credit Control' },
  { key: 'approve_credit_director', label: 'Credit: Director Approve' },
  { key: 'approve_credit_manager', label: 'Credit: Manager Approve' },
  { key: 'view_credit_repayment_approvals', label: 'Credit Repayment Approvals' },
  { key: 'view_approvals', label: 'Approvals Center' },
  { key: 'approve_wholesale_director', label: 'Wholesale: Director Approve' },
  { key: 'approve_wholesale_manager', label: 'Wholesale: Manager Approve' },
  { key: 'view_refunds', label: 'Refunds' },
  { key: 'add_refunds', label: 'Refunds: Add Request' },
  { key: 'approve_refunds', label: 'Refunds: Approve/Reject' },
  { key: 'view_expenses', label: 'Expenses' },
  { key: 'add_expenses', label: 'Expenses: Add/Delete' },
  { key: 'approve_expenses', label: 'Expenses: Approve/Reject' },
  { key: 'view_reports', label: 'Reports' },
  { key: 'view_stock_records', label: 'Stock Records' },
  { key: 'view_wholesale_invoices', label: 'Wholesale Invoices' },
  { key: 'view_warehouse_invoices', label: 'Warehouse Invoices' },
  { key: 'view_warehouse_approvals', label: 'Warehouse Approvals' },
  { key: 'view_imei_conflicts', label: 'IMEI Conflicts' },
  { key: 'view_cashdrawer', label: 'Cash Drawer' },
  { key: 'view_users', label: 'Users' },
  { key: 'view_config', label: 'Config' },
  { key: 'view_audit', label: 'Audit Log' }
];

export const GRANT_FEATURE_MAP = Object.fromEntries(
  TENANT_GRANT_CATALOG.map((item) => [item.key, `grants.${item.key}`])
);

export const TENANT_FEATURE_CATALOG = [
  { key: 'modules.dashboard', label: 'Dashboard', group: 'Main Menus' },
  { key: 'modules.pos', label: 'POS', group: 'Main Menus' },
  { key: 'modules.wholesalePos', label: 'Wholesale POS', group: 'Main Menus' },
  { key: 'modules.invoices', label: 'Invoices', group: 'Main Menus' },
  { key: 'modules.sales', label: 'Sales', group: 'Main Menus' },
  { key: 'modules.products', label: 'Products', group: 'Main Menus' },
  { key: 'modules.inventory', label: 'Inventory', group: 'Main Menus' },
  { key: 'modules.labels', label: 'Labels', group: 'Main Menus' },
  { key: 'modules.purchases', label: 'Purchases', group: 'Main Menus' },
  { key: 'modules.expenses', label: 'Expenses', group: 'Main Menus' },
  { key: 'modules.transfers', label: 'Transfers', group: 'Main Menus' },
  { key: 'modules.adjustments', label: 'Adjustments', group: 'Main Menus' },
  { key: 'modules.suppliers', label: 'Suppliers', group: 'Main Menus' },
  { key: 'modules.customers', label: 'Customers', group: 'Main Menus' },
  { key: 'modules.creditControl', label: 'Credit Control', group: 'Main Menus' },
  { key: 'modules.approvalsCenter', label: 'Approvals Center', group: 'Main Menus' },
  { key: 'modules.refunds', label: 'Refunds', group: 'Main Menus' },
  { key: 'modules.refundApprovals', label: 'Refund Approvals', group: 'Main Menus' },
  { key: 'modules.expenseApprovals', label: 'Expense Approvals', group: 'Main Menus' },
  { key: 'modules.reports', label: 'Reports', group: 'Main Menus' },
  { key: 'modules.backup', label: 'Backup', group: 'Main Menus' },
  { key: 'admin.users', label: 'Users', group: 'Admin Menus' },
  { key: 'admin.manual', label: 'Manual', group: 'Admin Menus' },
  { key: 'admin.audit', label: 'Audit Log', group: 'Admin Menus' },
  { key: 'admin.serverLogs', label: 'Server Logs', group: 'Admin Menus' },
  { key: 'admin.stockRecords', label: 'Stock Records', group: 'Admin Menus' },
  { key: 'admin.cashDrawer', label: 'Cash Drawer', group: 'Admin Menus' },
  { key: 'admin.config', label: 'Config', group: 'Admin Menus' },
  { key: 'admin.godhand', label: 'GodHand', group: 'Admin Menus' },
  { key: 'admin.docs', label: 'Docs', group: 'Admin Menus' },
  { key: 'features.offlineBackup', label: 'Offline usage (queue + backup)', group: 'Features' },
  { key: 'tabs.customerPurchaseHistory', label: 'Customer Purchase History', group: 'Tabs' },
  { key: 'tabs.posHeldSales', label: 'POS - Held Sales panel', group: 'Tabs' },
  { key: 'tabs.invoiceNew', label: 'Invoices - New Invoice tab', group: 'Tabs' },
  { key: 'tabs.invoiceRecords', label: 'Invoices - Records tab', group: 'Tabs' },
  ...TENANT_GRANT_CATALOG.map((item) => ({ key: `grants.${item.key}`, label: item.label, group: 'Grant Access' }))
];

export function filterGrantsByTenantFlags(grants, settings) {
  const flags = settings?.featureFlags || {};
  return (Array.isArray(grants) ? grants : []).filter((grant) => flags[GRANT_FEATURE_MAP[String(grant)] || ''] !== false);
}
